#c_compiler_version:
#  - 9.0 # [linux]

#cxx_compiler_version:
#  - 9.0 # [linux]

c_compiler:
  # - vs2022 # [win]
  #- gcc >=9.0 # [linux]
  - clang     # [osx]

cxx_compiler:
  # - vs2022 # [win]
  #- gxx >=9.0 # [linux]
  - clangxx   # [osx]
